### ISSUE TITLE
Add Impersonation

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-invitations#8]
- [x] Upgrade to latest stable version of node
 - [x] Add the ability to impersonate requests using `API_SECRET:username` as a authToken.

**Comment by elmigranto** [comment]
I believe usernames are `/[a-z0-9]+/i`, and j3k0/ganomede-helpers#5 uses `.` as separator for this, so let's roll with that in current and other similar issues. If that's not the case, I'll update helpers accordingly.

**Comment by j3k0** [comment]
`.` works fine as a separator. (At least `space`, `.`, `/` and `:` are forbidden characters in usernames)
